packages:
  - 'apps/*'
  - 'packages/*'

supportedArchitectures:
  os:
    - current
    - linux
  cpu:
    - current
    - arm64
    - x64

publicHoistPattern:
  - lightningcss-*

onlyBuiltDependencies:
  - sharp
  - esbuild
  - lightningcss
  - unrs-resolver